[mypy]
python_version = 3.12
show_error_codes = True
follow_imports = silent
ignore_missing_imports = True
strict_equality = True
warn_unreachable = False
warn_redundant_casts = True
warn_unused_ignores = True
check_untyped_defs = True
disable_error_code = attr-defined, type-arg, call-arg, override, valid-type, assignment, arg-type

[mypy-custom_components.modern_forms.*]
ignore_errors = False
